import type { SourceType, ExtractionMethod } from './provenance.js';

export type ImportBatchStatus = 'pending' | 'running' | 'completed' | 'failed';

/**
 * Tracks one import operation — a single run of a connector, file import, or
 * agent-assisted extraction. Every canonical Transaction points back to a batch.
 */
export interface ImportBatch {
  /** UUID generated by the caller before the import run begins. */
  id: string;
  /** ISO 8601 creation timestamp. */
  createdAt: string;
  sourceType: SourceType;
  /** Original filename for file-based imports. */
  sourceFile?: string;
  /** Connector id for scraper-based imports, e.g. 'hapoalim'. */
  connectorId?: string;
  /** Canonical account IDs affected — populated after normalization. */
  accountIds: string[];
  transactionCount: number;
  status: ImportBatchStatus;
  errorMessage?: string;
  extractionMethod: ExtractionMethod;
  /** Provider/scraper/model used for this batch. */
  providerUsed?: string;
  extractorVersion?: string;
}

/** Creates a new pending batch with a generated id and current timestamp. */
export function createImportBatch(
  opts: Omit<ImportBatch, 'id' | 'createdAt' | 'accountIds' | 'transactionCount' | 'status'>,
): ImportBatch {
  return {
    ...opts,
    id: generateBatchId(),
    createdAt: new Date().toISOString(),
    accountIds: [],
    transactionCount: 0,
    status: 'pending',
  };
}

function generateBatchId(): string {
  // Timestamp + random suffix — no crypto dep for this non-security id
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 10);
  return `batch-${ts}-${rand}`;
}
